/* ================================================================== */
/*
 * test_binding.c
 * A primitive program to test a minimal binding.
 *
 * This file is part of LuaSDL.
 *
 * PUBLIC DOMAIN. Author: Kein-Hong Man <khman@users.sf.net> 2007
 */
/* ================================================================== */

/* ================================================================== */
/*
 * For program behaviour, see: test_binding.lua
 */
/* ================================================================== */

#include <stdlib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "SDL.h"

#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
#include "tolua++.h"

/* header file of autogenerated binding */
#include "autogen/test_SDL_bind.h"

#if defined(LUA_VERSION_NUM) && LUA_VERSION_NUM < 501
#error "requires Lua 5.1 or better, unless you know what you are doing"
#endif

static int lua_dofile(lua_State *L, const char *filename)
{
    int status = luaL_loadfile(L, filename)
              || lua_pcall(L, 0, LUA_MULTRET, 0);
    if (status && !lua_isnil(L, -1)) {
        const char *msg = lua_tostring(L, -1);
        if (msg == NULL) msg = "(error object is not a string)";
        fprintf(stderr, "%s\n", msg);
        fflush(stderr);
    }
    return status;
}

int main(int argc, char *argv[])
{
    lua_State* L = lua_open();
    luaL_openlibs(L);
    tolua_test_SDL_open(L);
    /* try dostring first if dofile does not work */
    //luaL_dostring(L, "print([[hello, world!]])");
    lua_dofile(L, "test_binding.lua");
    lua_close(L);
    return 0;
}
